
exports.seed = function(knex) {
    // Deletes ALL existing entries
    return knex('fpl.players').del()
      .then(function () {
        // Inserts seed entries
        return knex('fpl.players').insert([
          {player_id: '1', player_nm: 'Bernd Leno', player_pos: 'GKP'},
          {player_id: '2', player_nm: 'Rúnar Alex Rúnarsson', player_pos: 'GKP'},
          {player_id: '3', player_nm: 'Willian Borges Da Silva', player_pos: 'MID'},
          {player_id: '4', player_nm: 'Pierre-Emerick Aubameyang', player_pos: 'FWD'},
          {player_id: '5', player_nm: 'Cédric Soares', player_pos: 'DEF'},
          {player_id: '6', player_nm: 'Alexandre Lacazette', player_pos: 'FWD'},
          {player_id: '7', player_nm: 'Granit Xhaka', player_pos: 'MID'},
          {player_id: '8', player_nm: 'Pablo Marí', player_pos: 'DEF'},
          {player_id: '9', player_nm: 'Héctor Bellerín', player_pos: 'DEF'},
          {player_id: '10', player_nm: 'Calum Chambers', player_pos: 'DEF'},
          {player_id: '11', player_nm: 'Sead Kolasinac', player_pos: 'DEF'},
          {player_id: '12', player_nm: 'Mohamed Naser El Sayed Elneny', player_pos: 'MID'},
          {player_id: '13', player_nm: 'Ainsley Maitland-Niles', player_pos: 'MID'},
          {player_id: '14', player_nm: 'Rob Holding', player_pos: 'DEF'},
          {player_id: '15', player_nm: 'Thomas Partey', player_pos: 'MID'},
          {player_id: '16', player_nm: 'Kieran Tierney', player_pos: 'DEF'},
          {player_id: '17', player_nm: 'Nicolas Pépé', player_pos: 'MID'},
          {player_id: '18', player_nm: 'Lucas Torreira', player_pos: 'MID'},
          {player_id: '20', player_nm: 'Edward Nketiah', player_pos: 'FWD'},
          {player_id: '21', player_nm: 'Emile Smith Rowe', player_pos: 'MID'},
          {player_id: '22', player_nm: 'Bukayo Saka', player_pos: 'MID'},
          {player_id: '23', player_nm: 'Gabriel Magalhães', player_pos: 'DEF'},
          {player_id: '24', player_nm: 'Konstantinos Mavropanos', player_pos: 'DEF'},
          {player_id: '25', player_nm: 'Mattéo Guendouzi', player_pos: 'MID'},
          {player_id: '26', player_nm: 'Gabriel Teodoro Martinelli Silva', player_pos: 'MID'},
          {player_id: '27', player_nm: 'William Saliba', player_pos: 'DEF'},
          {player_id: '67', player_nm: 'Ben White', player_pos: 'DEF'},
          {player_id: '466', player_nm: 'Nuno Varela Tavares', player_pos: 'DEF'},
          {player_id: '478', player_nm: 'Albert Sambi Lokonga', player_pos: 'MID'},
          {player_id: '530', player_nm: 'Folarin Balogun', player_pos: 'FWD'},
          {player_id: '531', player_nm: 'Reiss Nelson', player_pos: 'MID'},
          {player_id: '532', player_nm: 'Karl Hein', player_pos: 'GKP'},
          {player_id: '558', player_nm: 'Martin Ødegaard', player_pos: 'MID'},
          {player_id: '559', player_nm: 'Aaron Ramsdale', player_pos: 'GKP'},
          {player_id: '572', player_nm: 'Arthur Okonkwo', player_pos: 'GKP'},
          {player_id: '590', player_nm: 'Takehiro Tomiyasu', player_pos: 'DEF'},
          {player_id: '28', player_nm: 'Jed Steer', player_pos: 'GKP'},
          {player_id: '29', player_nm: 'Conor Hourihane', player_pos: 'MID'},
          {player_id: '30', player_nm: 'Emiliano Martínez', player_pos: 'GKP'},
          {player_id: '31', player_nm: 'Björn Engels', player_pos: 'DEF'},
          {player_id: '32', player_nm: 'Bertrand Traoré', player_pos: 'MID'},
          {player_id: '34', player_nm: 'Morgan Sanson', player_pos: 'MID'},
          {player_id: '35', player_nm: 'John McGinn', player_pos: 'MID'},
          {player_id: '36', player_nm: 'Kortney Hause', player_pos: 'DEF'},
          {player_id: '37', player_nm: 'Mahmoud Ahmed Ibrahim Hassan', player_pos: 'MID'},
          {player_id: '38', player_nm: 'Tyrone Mings', player_pos: 'DEF'},
          {player_id: '39', player_nm: 'Matt Targett', player_pos: 'DEF'},
          {player_id: '40', player_nm: 'Ollie Watkins', player_pos: 'FWD'},
          {player_id: '41', player_nm: 'Marvelous Nakamba', player_pos: 'MID'},
          {player_id: '42', player_nm: 'Anwar El Ghazi', player_pos: 'MID'},
          {player_id: '43', player_nm: 'Emiliano Buendía Stati', player_pos: 'MID'},
          {player_id: '44', player_nm: 'Matthew Cash', player_pos: 'DEF'},
          {player_id: '45', player_nm: 'Ezri Konsa Ngoyo', player_pos: 'DEF'},
          {player_id: '46', player_nm: 'Frédéric Guilbert', player_pos: 'DEF'},
          {player_id: '47', player_nm: 'Wesley Moraes', player_pos: 'FWD'},
          {player_id: '48', player_nm: 'Mbwana Ally Samatta', player_pos: 'FWD'},
          {player_id: '49', player_nm: 'Keinan Davis', player_pos: 'FWD'},
          {player_id: '50', player_nm: 'Douglas Luiz Soares de Paulo', player_pos: 'MID'},
          {player_id: '51', player_nm: 'Jacob Ramsey', player_pos: 'MID'},
          {player_id: '52', player_nm: 'Ashley Young', player_pos: 'DEF'},
          {player_id: '283', player_nm: 'Axel Tuanzebe', player_pos: 'DEF'},
          {player_id: '337', player_nm: 'Danny Ings', player_pos: 'FWD'},
          {player_id: '492', player_nm: 'Leon Bailey', player_pos: 'MID'},
          {player_id: '496', player_nm: 'Aaron Ramsey', player_pos: 'MID'},
          {player_id: '497', player_nm: 'Jaden Philogene-Bidace', player_pos: 'MID'},
          {player_id: '526', player_nm: 'Carney Chukwuemeka', player_pos: 'MID'},
          {player_id: '568', player_nm: 'Cameron Archer', player_pos: 'FWD'},
          {player_id: '596', player_nm: 'Viljami Sinisalo', player_pos: 'GKP'},
          {player_id: '610', player_nm: 'Lamare Bogarde', player_pos: 'DEF'},
          {player_id: '76', player_nm: 'Pontus Jansson', player_pos: 'DEF'},
          {player_id: '77', player_nm: 'Christian Nørgaard', player_pos: 'MID'},
          {player_id: '78', player_nm: 'Ivan Toney', player_pos: 'FWD'},
          {player_id: '79', player_nm: 'Tariqe Fosu-Henry', player_pos: 'MID'},
          {player_id: '80', player_nm: 'David Raya Martin', player_pos: 'GKP'},
          {player_id: '81', player_nm: 'Sergi Canós', player_pos: 'MID'},
          {player_id: '82', player_nm: 'Pelenda Joshua Dasilva', player_pos: 'MID'},
          {player_id: '83', player_nm: 'Rico Henry', player_pos: 'DEF'},
          {player_id: '84', player_nm: 'Vitaly Janelt', player_pos: 'MID'},
          {player_id: '85', player_nm: 'Saman Ghoddos', player_pos: 'MID'},
          {player_id: '86', player_nm: 'Mathias Jensen', player_pos: 'MID'},
          {player_id: '87', player_nm: 'Charlie Goode', player_pos: 'DEF'},
          {player_id: '88', player_nm: 'Marcus Forss', player_pos: 'FWD'},
          {player_id: '89', player_nm: 'Mads Roerslev Rasmussen', player_pos: 'DEF'},
          {player_id: '90', player_nm: 'Mads Bech Sørensen', player_pos: 'DEF'},
          {player_id: '91', player_nm: 'Ethan Pinnock', player_pos: 'DEF'},
          {player_id: '92', player_nm: 'Ellery Balcombe', player_pos: 'GKP'},
          {player_id: '93', player_nm: 'Jan Zamburek', player_pos: 'MID'},
          {player_id: '94', player_nm: 'Patrik Gunnarsson', player_pos: 'GKP'},
          {player_id: '95', player_nm: 'Halil Dervişoğlu', player_pos: 'FWD'},
          {player_id: '96', player_nm: 'Bryan Mbeumo', player_pos: 'MID'},
          {player_id: '97', player_nm: 'Mads Bidstrup', player_pos: 'MID'},
          {player_id: '479', player_nm: 'Frank Onyeka', player_pos: 'MID'},
          {player_id: '483', player_nm: 'Kristoffer Ajer', player_pos: 'DEF'},
          {player_id: '498', player_nm: 'Dominic Thompson', player_pos: 'DEF'},
          {player_id: '499', player_nm: 'Shandon Baptiste', player_pos: 'MID'},
          {player_id: '524', player_nm: 'Yoane Wissa', player_pos: 'MID'},
          {player_id: '556', player_nm: 'Álvaro Fernández', player_pos: 'GKP'},
          {player_id: '569', player_nm: 'Finley Stevens', player_pos: 'DEF'},
          {player_id: '594', player_nm: 'Mathias Jorgensen', player_pos: 'DEF'},
          {player_id: '614', player_nm: 'Paris Maghoma', player_pos: 'MID'},
          {player_id: '619', player_nm: 'Matthew Cox', player_pos: 'GKP'},
          {player_id: '53', player_nm: 'Adam Lallana', player_pos: 'MID'},
          {player_id: '54', player_nm: 'Jason Steele', player_pos: 'GKP'},
          {player_id: '55', player_nm: 'Pascal Groß', player_pos: 'MID'},
          {player_id: '56', player_nm: 'Shane Duffy', player_pos: 'DEF'},
          {player_id: '57', player_nm: 'Davy Pröpper', player_pos: 'MID'},
          {player_id: '58', player_nm: 'Dan Burn', player_pos: 'DEF'},
          {player_id: '59', player_nm: 'Lewis Dunk', player_pos: 'DEF'},
          {player_id: '60', player_nm: 'Solomon March', player_pos: 'MID'},
          {player_id: '61', player_nm: 'Adam Webster', player_pos: 'DEF'},
          {player_id: '62', player_nm: 'Joël Veltman', player_pos: 'DEF'},
          {player_id: '63', player_nm: 'Neal Maupay', player_pos: 'FWD'},
          {player_id: '64', player_nm: 'Leandro Trossard', player_pos: 'MID'},
          {player_id: '65', player_nm: 'Mathew Ryan', player_pos: 'GKP'},
          {player_id: '66', player_nm: 'Alireza Jahanbakhsh', player_pos: 'MID'},
          {player_id: '68', player_nm: 'Bernardo Fernandes Da Silva Junior', player_pos: 'DEF'},
          {player_id: '69', player_nm: 'Robert Sánchez', player_pos: 'GKP'},
          {player_id: '70', player_nm: 'Yves Bissouma', player_pos: 'MID'},
          {player_id: '71', player_nm: 'Tariq Lamptey', player_pos: 'DEF'},
          {player_id: '72', player_nm: 'Aaron Connolly', player_pos: 'FWD'},
          {player_id: '73', player_nm: 'Steven Alzate', player_pos: 'MID'},
          {player_id: '74', player_nm: 'Alexis Mac Allister', player_pos: 'MID'},
          {player_id: '75', player_nm: 'Jakub Moder', player_pos: 'MID'},
          {player_id: '447', player_nm: 'Danny Welbeck', player_pos: 'FWD'},
          {player_id: '462', player_nm: 'Enock Mwepu', player_pos: 'MID'},
          {player_id: '476', player_nm: 'Kjell Scherpen', player_pos: 'GKP'},
          {player_id: '500', player_nm: 'Florin Andone', player_pos: 'FWD'},
          {player_id: '535', player_nm: 'Andi Zeqiri', player_pos: 'FWD'},
          {player_id: '536', player_nm: 'Michal Karbownik', player_pos: 'DEF'},
          {player_id: '537', player_nm: 'Taylor Richards', player_pos: 'MID'},
          {player_id: '538', player_nm: 'Moisés Caicedo', player_pos: 'MID'},
          {player_id: '560', player_nm: 'Haydon Roberts', player_pos: 'DEF'},
          {player_id: '584', player_nm: 'Marc Cucurella', player_pos: 'DEF'},
          {player_id: '595', player_nm: 'Jürgen Locadia', player_pos: 'FWD'},
          {player_id: '612', player_nm: 'Jeremy Sarmiento', player_pos: 'MID'},
          {player_id: '98', player_nm: 'James Tarkowski', player_pos: 'DEF'},
          {player_id: '99', player_nm: 'Phil Bardsley', player_pos: 'DEF'},
          {player_id: '100', player_nm: 'Erik Pieters', player_pos: 'DEF'},
          {player_id: '101', player_nm: 'Jack Cork', player_pos: 'MID'},
          {player_id: '102', player_nm: 'Dale Stephens', player_pos: 'MID'},
          {player_id: '103', player_nm: 'Kevin Long', player_pos: 'DEF'},
          {player_id: '104', player_nm: 'Jay Rodriguez', player_pos: 'FWD'},
          {player_id: '105', player_nm: 'Ashley Barnes', player_pos: 'FWD'},
          {player_id: '106', player_nm: 'Ben Mee', player_pos: 'DEF'},
          {player_id: '107', player_nm: 'Ashley Westwood', player_pos: 'MID'},
          {player_id: '108', player_nm: 'Johann Berg Gudmundsson', player_pos: 'MID'},
          {player_id: '109', player_nm: 'Chris Wood', player_pos: 'FWD'},
          {player_id: '110', player_nm: 'Matthew Lowton', player_pos: 'DEF'},
          {player_id: '111', player_nm: 'Matej Vydra', player_pos: 'FWD'},
          {player_id: '112', player_nm: 'Nick Pope', player_pos: 'GKP'},
          {player_id: '113', player_nm: 'Charlie Taylor', player_pos: 'DEF'},
          {player_id: '114', player_nm: 'Will Norris', player_pos: 'GKP'},
          {player_id: '115', player_nm: 'Josh Brownhill', player_pos: 'MID'},
          {player_id: '116', player_nm: 'Josh Benson', player_pos: 'MID'},
          {player_id: '117', player_nm: 'Bailey Peacock-Farrell', player_pos: 'GKP'},
          {player_id: '118', player_nm: 'Dwight McNeil', player_pos: 'MID'},
          {player_id: '451', player_nm: 'Nathan Collins', player_pos: 'DEF'},
          {player_id: '480', player_nm: 'Wayne Hennessey', player_pos: 'GKP'},
          {player_id: '533', player_nm: 'Lewis Richardson', player_pos: 'FWD'},
          {player_id: '534', player_nm: 'Bobby Thomas', player_pos: 'DEF'},
          {player_id: '565', player_nm: 'Owen Dodgson', player_pos: 'DEF'},
          {player_id: '575', player_nm: 'Aaron Lennon', player_pos: 'MID'},
          {player_id: '578', player_nm: 'Maxwel Cornet', player_pos: 'MID'},
          {player_id: '585', player_nm: 'Connor Roberts', player_pos: 'DEF'},
          {player_id: '119', player_nm: 'César Azpilicueta', player_pos: 'DEF'},
          {player_id: '120', player_nm: 'Olivier Giroud', player_pos: 'FWD'},
          {player_id: '121', player_nm: 'Thiago Emiliano da Silva', player_pos: 'DEF'},
          {player_id: '122', player_nm: 'Marcos Alonso', player_pos: 'DEF'},
          {player_id: '123', player_nm: 'Jorge Luiz Frello Filho', player_pos: 'MID'},
          {player_id: '124', player_nm: 'Ross Barkley', player_pos: 'MID'},
          {player_id: '125', player_nm: 'Mateo Kovacic', player_pos: 'MID'},
          {player_id: '126', player_nm: 'Michy Batshuayi', player_pos: 'FWD'},
          {player_id: '127', player_nm: 'Antonio Rüdiger', player_pos: 'DEF'},
          {player_id: '129', player_nm: 'Kepa Arrizabalaga', player_pos: 'GKP'},
          {player_id: '130', player_nm: 'NGolo Kanté', player_pos: 'MID'},
          {player_id: '131', player_nm: 'Hakim Ziyech', player_pos: 'MID'},
          {player_id: '132', player_nm: 'Ruben Loftus-Cheek', player_pos: 'MID'},
          {player_id: '133', player_nm: 'Andreas Christensen', player_pos: 'DEF'},
          {player_id: '134', player_nm: 'Timo Werner', player_pos: 'FWD'},
          {player_id: '135', player_nm: 'Benjamin Chilwell', player_pos: 'DEF'},
          {player_id: '136', player_nm: 'Tammy Abraham', player_pos: 'FWD'},
          {player_id: '137', player_nm: 'Christian Pulisic', player_pos: 'MID'},
          {player_id: '138', player_nm: 'Mason Mount', player_pos: 'MID'},
          {player_id: '139', player_nm: 'Ethan Ampadu', player_pos: 'DEF'},
          {player_id: '140', player_nm: 'Callum Hudson-Odoi', player_pos: 'MID'},
          {player_id: '141', player_nm: 'Kai Havertz', player_pos: 'MID'},
          {player_id: '142', player_nm: 'Reece James', player_pos: 'DEF'},
          {player_id: '143', player_nm: 'Edouard Mendy', player_pos: 'GKP'},
          {player_id: '501', player_nm: 'Malang Sarr', player_pos: 'DEF'},
          {player_id: '527', player_nm: 'Trevoh Chalobah', player_pos: 'DEF'},
          {player_id: '529', player_nm: 'Romelu Lukaku', player_pos: 'FWD'},
          {player_id: '539', player_nm: 'Emerson Palmieri dos Santos', player_pos: 'DEF'},
          {player_id: '592', player_nm: 'Saúl Ñíguez', player_pos: 'MID'},
          {player_id: '606', player_nm: 'Marcus Bettinelli', player_pos: 'GKP'},
          {player_id: '144', player_nm: 'Conor Gallagher', player_pos: 'MID'},
          {player_id: '146', player_nm: 'Vicente Guaita', player_pos: 'GKP'},
          {player_id: '147', player_nm: 'James Tomkins', player_pos: 'DEF'},
          {player_id: '148', player_nm: 'James McArthur', player_pos: 'MID'},
          {player_id: '149', player_nm: 'Christian Benteke', player_pos: 'FWD'},
          {player_id: '150', player_nm: 'Cheikhou Kouyaté', player_pos: 'DEF'},
          {player_id: '151', player_nm: 'Martin Kelly', player_pos: 'DEF'},
          {player_id: '152', player_nm: 'Luka Milivojevic', player_pos: 'MID'},
          {player_id: '153', player_nm: 'Jordan Ayew', player_pos: 'FWD'},
          {player_id: '154', player_nm: 'Wilfried Zaha', player_pos: 'MID'},
          {player_id: '155', player_nm: 'Jeffrey Schlupp', player_pos: 'MID'},
          {player_id: '156', player_nm: 'Jack Butland', player_pos: 'GKP'},
          {player_id: '157', player_nm: 'Jairo Riedewald', player_pos: 'MID'},
          {player_id: '158', player_nm: 'Jarosław Jach', player_pos: 'DEF'},
          {player_id: '159', player_nm: 'Jean-Philippe Mateta', player_pos: 'FWD'},
          {player_id: '160', player_nm: 'Eberechi Eze', player_pos: 'MID'},
          {player_id: '161', player_nm: 'Nathan Ferguson', player_pos: 'DEF'},
          {player_id: '162', player_nm: 'Tyrick Mitchell', player_pos: 'DEF'},
          {player_id: '386', player_nm: 'Will Hughes', player_pos: 'MID'},
          {player_id: '464', player_nm: 'Michael Olise', player_pos: 'MID'},
          {player_id: '474', player_nm: 'Joel Ward', player_pos: 'DEF'},
          {player_id: '477', player_nm: 'Marc Guéhi', player_pos: 'DEF'},
          {player_id: '488', player_nm: 'Joachim Andersen', player_pos: 'DEF'},
          {player_id: '493', player_nm: 'Nathaniel Clyne', player_pos: 'DEF'},
          {player_id: '540', player_nm: 'Reece Hannam', player_pos: 'DEF'},
          {player_id: '541', player_nm: 'Jesurun Rak-Sakyi', player_pos: 'MID'},
          {player_id: '542', player_nm: 'Robert Street', player_pos: 'FWD'},
          {player_id: '543', player_nm: 'Scott Banks', player_pos: 'MID'},
          {player_id: '561', player_nm: 'Remi Matthews', player_pos: 'GKP'},
          {player_id: '586', player_nm: 'Odsonne Edouard', player_pos: 'FWD'},
          {player_id: '163', player_nm: 'Fabian Delph', player_pos: 'MID'},
          {player_id: '164', player_nm: 'Gylfi Sigurdsson', player_pos: 'MID'},
          {player_id: '165', player_nm: 'Seamus Coleman', player_pos: 'DEF'},
          {player_id: '166', player_nm: 'James Rodríguez', player_pos: 'MID'},
          {player_id: '167', player_nm: 'Bernard Anício Caldeira Duarte', player_pos: 'MID'},
          {player_id: '168', player_nm: 'Lucas Digne', player_pos: 'DEF'},
          {player_id: '169', player_nm: 'Michael Keane', player_pos: 'DEF'},
          {player_id: '170', player_nm: 'Jordan Pickford', player_pos: 'GKP'},
          {player_id: '171', player_nm: 'Allan Marques Loureiro', player_pos: 'MID'},
          {player_id: '172', player_nm: 'André Filipe Tavares Gomes', player_pos: 'MID'},
          {player_id: '173', player_nm: 'Abdoulaye Doucouré', player_pos: 'MID'},
          {player_id: '174', player_nm: 'Alex Iwobi', player_pos: 'MID'},
          {player_id: '175', player_nm: 'Yerry Mina', player_pos: 'DEF'},
          {player_id: '176', player_nm: 'Tom Davies', player_pos: 'MID'},
          {player_id: '177', player_nm: 'Dominic Calvert-Lewin', player_pos: 'FWD'},
          {player_id: '178', player_nm: 'Mason Holgate', player_pos: 'DEF'},
          {player_id: '179', player_nm: 'Ben Godfrey', player_pos: 'DEF'},
          {player_id: '180', player_nm: 'Richarlison de Andrade', player_pos: 'FWD'},
          {player_id: '181', player_nm: 'João Virgínia', player_pos: 'GKP'},
          {player_id: '481', player_nm: 'Asmir Begović', player_pos: 'GKP'},
          {player_id: '482', player_nm: 'Andros Townsend', player_pos: 'MID'},
          {player_id: '484', player_nm: 'Demarai Gray', player_pos: 'MID'},
          {player_id: '502', player_nm: 'Jonjoe Kenny', player_pos: 'DEF'},
          {player_id: '503', player_nm: 'Anthony Gordon', player_pos: 'MID'},
          {player_id: '504', player_nm: 'Jean-Philippe Gbamin', player_pos: 'MID'},
          {player_id: '544', player_nm: 'Jarrad Branthwaite', player_pos: 'DEF'},
          {player_id: '545', player_nm: 'Nathan Broadhead', player_pos: 'FWD'},
          {player_id: '564', player_nm: 'Moise Kean', player_pos: 'FWD'},
          {player_id: '570', player_nm: 'Niels Nkounkou', player_pos: 'DEF'},
          {player_id: '571', player_nm: 'Andy Lonergan', player_pos: 'GKP'},
          {player_id: '591', player_nm: 'Salomón Rondón', player_pos: 'FWD'},
          {player_id: '602', player_nm: 'Ellis Simms', player_pos: 'FWD'},
          {player_id: '607', player_nm: 'Lewis Dobbin', player_pos: 'FWD'},
          {player_id: '613', player_nm: 'Charlie Whitaker', player_pos: 'MID'},
          {player_id: '616', player_nm: 'Harry Tyrer', player_pos: 'GKP'},
          {player_id: '622', player_nm: 'Cenk Tosun', player_pos: 'FWD'},
          {player_id: '623', player_nm: 'Reece Welch', player_pos: 'DEF'},
          {player_id: '200', player_nm: 'Kasper Schmeichel', player_pos: 'GKP'},
          {player_id: '201', player_nm: 'Jonny Evans', player_pos: 'DEF'},
          {player_id: '202', player_nm: 'Marc Albrighton', player_pos: 'MID'},
          {player_id: '203', player_nm: 'Nampalys Mendy', player_pos: 'MID'},
          {player_id: '204', player_nm: 'Danny Ward', player_pos: 'GKP'},
          {player_id: '205', player_nm: 'Jamie Vardy', player_pos: 'FWD'},
          {player_id: '206', player_nm: 'Dennis Praet', player_pos: 'MID'},
          {player_id: '207', player_nm: 'Ricardo Domingos Barbosa Pereira', player_pos: 'DEF'},
          {player_id: '208', player_nm: 'Daniel Amartey', player_pos: 'DEF'},
          {player_id: '209', player_nm: 'Timothy Castagne', player_pos: 'DEF'},
          {player_id: '210', player_nm: 'Youri Tielemans', player_pos: 'MID'},
          {player_id: '211', player_nm: 'Ayoze Pérez', player_pos: 'MID'},
          {player_id: '212', player_nm: 'James Maddison', player_pos: 'MID'},
          {player_id: '213', player_nm: 'Kelechi Iheanacho', player_pos: 'FWD'},
          {player_id: '214', player_nm: 'Hamza Choudhury', player_pos: 'MID'},
          {player_id: '215', player_nm: 'Harvey Barnes', player_pos: 'MID'},
          {player_id: '216', player_nm: 'Wilfred Ndidi', player_pos: 'MID'},
          {player_id: '217', player_nm: 'Çaglar Söyüncü', player_pos: 'DEF'},
          {player_id: '218', player_nm: 'James Justin', player_pos: 'DEF'},
          {player_id: '219', player_nm: 'Luke Thomas', player_pos: 'DEF'},
          {player_id: '220', player_nm: 'Wesley Fofana', player_pos: 'DEF'},
          {player_id: '340', player_nm: 'Jannik Vestergaard', player_pos: 'DEF'},
          {player_id: '455', player_nm: 'Patson Daka', player_pos: 'FWD'},
          {player_id: '458', player_nm: 'Boubakary Soumaré', player_pos: 'MID'},
          {player_id: '473', player_nm: 'Ryan Bertrand', player_pos: 'DEF'},
          {player_id: '505', player_nm: 'Kiernan Dewsbury-Hall', player_pos: 'MID'},
          {player_id: '573', player_nm: 'Eldin Jakupovic', player_pos: 'GKP'},
          {player_id: '587', player_nm: 'Ademola Lookman', player_pos: 'MID'},
          {player_id: '182', player_nm: 'Pablo Hernández Domínguez', player_pos: 'MID'},
          {player_id: '183', player_nm: 'Francisco Casilla Cortés', player_pos: 'GKP'},
          {player_id: '184', player_nm: 'Liam Cooper', player_pos: 'DEF'},
          {player_id: '185', player_nm: 'Luke Ayling', player_pos: 'DEF'},
          {player_id: '186', player_nm: 'Mateusz Klich', player_pos: 'MID'},
          {player_id: '187', player_nm: 'Rodrigo Moreno', player_pos: 'FWD'},
          {player_id: '188', player_nm: 'Stuart Dallas', player_pos: 'MID'},
          {player_id: '189', player_nm: 'Patrick Bamford', player_pos: 'FWD'},
          {player_id: '190', player_nm: 'Diego Llorente', player_pos: 'DEF'},
          {player_id: '191', player_nm: 'Kalvin Phillips', player_pos: 'MID'},
          {player_id: '192', player_nm: 'Hélder Wander Sousa de Azevedo e Costa', player_pos: 'MID'},
          {player_id: '193', player_nm: 'Tyler Roberts', player_pos: 'MID'},
          {player_id: '194', player_nm: 'Robin Koch', player_pos: 'DEF'},
          {player_id: '195', player_nm: 'Ian Carlo Poveda-Ocampo', player_pos: 'MID'},
          {player_id: '196', player_nm: 'Raphael Dias Belloli', player_pos: 'MID'},
          {player_id: '197', player_nm: 'Jamie Shackleton', player_pos: 'MID'},
          {player_id: '198', player_nm: 'Pascal Struijk', player_pos: 'DEF'},
          {player_id: '199', player_nm: 'Illan Meslier', player_pos: 'GKP'},
          {player_id: '267', player_nm: 'Jack Harrison', player_pos: 'MID'},
          {player_id: '287', player_nm: 'Daniel James', player_pos: 'MID'},
          {player_id: '463', player_nm: 'Héctor Junior Firpo Adames', player_pos: 'DEF'},
          {player_id: '490', player_nm: 'Kristoffer Klaesson', player_pos: 'GKP'},
          {player_id: '550', player_nm: 'Sam Greenwood', player_pos: 'FWD'},
          {player_id: '551', player_nm: 'Crysencio Summerville', player_pos: 'MID'},
          {player_id: '552', player_nm: 'Adam Forshaw', player_pos: 'MID'},
          {player_id: '562', player_nm: 'Cody Drameh', player_pos: 'DEF'},
          {player_id: '563', player_nm: 'Charlie Cresswell', player_pos: 'DEF'},
          {player_id: '576', player_nm: 'Liam McCarron', player_pos: 'MID'},
          {player_id: '577', player_nm: 'Joe Gelhardt', player_pos: 'FWD'},
          {player_id: '600', player_nm: 'Nohan Kenneh', player_pos: 'MID'},
          {player_id: '601', player_nm: 'Stuart McKinstry', player_pos: 'MID'},
          {player_id: '608', player_nm: 'Leo Fuhr Hjelde', player_pos: 'DEF'},
          {player_id: '221', player_nm: 'James Milner', player_pos: 'MID'},
          {player_id: '222', player_nm: 'Jordan Henderson', player_pos: 'MID'},
          {player_id: '223', player_nm: 'Adrián San Miguel del Castillo', player_pos: 'GKP'},
          {player_id: '224', player_nm: 'Joel Matip', player_pos: 'DEF'},
          {player_id: '225', player_nm: 'Thiago Alcántara do Nascimento', player_pos: 'MID'},
          {player_id: '226', player_nm: 'Xherdan Shaqiri', player_pos: 'MID'},
          {player_id: '227', player_nm: 'Alex Oxlade-Chamberlain', player_pos: 'MID'},
          {player_id: '228', player_nm: 'Roberto Firmino', player_pos: 'FWD'},
          {player_id: '229', player_nm: 'Virgil van Dijk', player_pos: 'DEF'},
          {player_id: '230', player_nm: 'Sadio Mané', player_pos: 'MID'},
          {player_id: '231', player_nm: 'Alisson Ramses Becker', player_pos: 'GKP'},
          {player_id: '232', player_nm: 'Fabio Henrique Tavares', player_pos: 'MID'},
          {player_id: '233', player_nm: 'Mohamed Salah', player_pos: 'MID'},
          {player_id: '234', player_nm: 'Andrew Robertson', player_pos: 'DEF'},
          {player_id: '235', player_nm: 'Divock Origi', player_pos: 'FWD'},
          {player_id: '236', player_nm: 'Takumi Minamino', player_pos: 'MID'},
          {player_id: '237', player_nm: 'Trent Alexander-Arnold', player_pos: 'DEF'},
          {player_id: '238', player_nm: 'Joseph Gomez', player_pos: 'DEF'},
          {player_id: '239', player_nm: 'Naby Keita', player_pos: 'MID'},
          {player_id: '240', player_nm: 'Diogo Jota', player_pos: 'MID'},
          {player_id: '241', player_nm: 'Nathaniel Phillips', player_pos: 'DEF'},
          {player_id: '242', player_nm: 'Caoimhin Kelleher', player_pos: 'GKP'},
          {player_id: '243', player_nm: 'Ibrahima Konaté', player_pos: 'DEF'},
          {player_id: '244', player_nm: 'Curtis Jones', player_pos: 'MID'},
          {player_id: '245', player_nm: 'Konstantinos Tsimikas', player_pos: 'DEF'},
          {player_id: '246', player_nm: 'Neco Williams', player_pos: 'DEF'},
          {player_id: '247', player_nm: 'Rhys Williams', player_pos: 'DEF'},
          {player_id: '248', player_nm: 'Ben Davies', player_pos: 'DEF'},
          {player_id: '506', player_nm: 'Harvey Elliott', player_pos: 'MID'},
          {player_id: '553', player_nm: 'Ben Woodburn', player_pos: 'MID'},
          {player_id: '620', player_nm: 'Tyler Morton', player_pos: 'MID'},
          {player_id: '33', player_nm: 'Jack Grealish', player_pos: 'MID'},
          {player_id: '249', player_nm: 'Kyle Walker', player_pos: 'DEF'},
          {player_id: '250', player_nm: 'Ilkay Gündogan', player_pos: 'MID'},
          {player_id: '251', player_nm: 'Kevin De Bruyne', player_pos: 'MID'},
          {player_id: '252', player_nm: 'John Stones', player_pos: 'DEF'},
          {player_id: '253', player_nm: 'Benjamin Mendy', player_pos: 'DEF'},
          {player_id: '254', player_nm: 'Riyad Mahrez', player_pos: 'MID'},
          {player_id: '255', player_nm: 'Raheem Sterling', player_pos: 'MID'},
          {player_id: '256', player_nm: 'João Pedro Cavaco Cancelo', player_pos: 'DEF'},
          {player_id: '257', player_nm: 'Ederson Santana de Moraes', player_pos: 'GKP'},
          {player_id: '258', player_nm: 'Nathan Aké', player_pos: 'DEF'},
          {player_id: '259', player_nm: 'Aymeric Laporte', player_pos: 'DEF'},
          {player_id: '260', player_nm: 'Zack Steffen', player_pos: 'GKP'},
          {player_id: '261', player_nm: 'Bernardo Mota Veiga de Carvalho e Silva', player_pos: 'MID'},
          {player_id: '262', player_nm: 'Rúben Santos Gato Alves Dias', player_pos: 'DEF'},
          {player_id: '263', player_nm: 'Gabriel Fernando de Jesus', player_pos: 'FWD'},
          {player_id: '264', player_nm: 'Oleksandr Zinchenko', player_pos: 'DEF'},
          {player_id: '265', player_nm: 'Phil Foden', player_pos: 'MID'},
          {player_id: '266', player_nm: 'Rodrigo Hernandez', player_pos: 'MID'},
          {player_id: '268', player_nm: 'Ferran Torres', player_pos: 'MID'},
          {player_id: '453', player_nm: 'Fernando Luiz Rosa', player_pos: 'MID'},
          {player_id: '507', player_nm: 'Cole Palmer', player_pos: 'MID'},
          {player_id: '508', player_nm: 'Samuel Edozie', player_pos: 'MID'},
          {player_id: '566', player_nm: 'Tommy Doyle', player_pos: 'MID'},
          {player_id: '593', player_nm: 'Scott Carson', player_pos: 'GKP'},
          {player_id: '603', player_nm: 'Luke Mbete', player_pos: 'DEF'},
          {player_id: '604', player_nm: 'Joshua Wilson-Esbrand', player_pos: 'DEF'},
          {player_id: '605', player_nm: 'Romeo Lavia', player_pos: 'MID'},
          {player_id: '615', player_nm: 'Cieran Slicker', player_pos: 'GKP'},
          {player_id: '269', player_nm: 'Edinson Cavani', player_pos: 'FWD'},
          {player_id: '270', player_nm: 'David de Gea', player_pos: 'GKP'},
          {player_id: '271', player_nm: 'Nemanja Matic', player_pos: 'MID'},
          {player_id: '272', player_nm: 'Paul Pogba', player_pos: 'MID'},
          {player_id: '273', player_nm: 'Harry Maguire', player_pos: 'DEF'},
          {player_id: '274', player_nm: 'Frederico Rodrigues de Paula Santos', player_pos: 'MID'},
          {player_id: '275', player_nm: 'Luke Shaw', player_pos: 'DEF'},
          {player_id: '276', player_nm: 'Jesse Lingard', player_pos: 'MID'},
          {player_id: '277', player_nm: 'Bruno Miguel Borges Fernandes', player_pos: 'MID'},
          {player_id: '278', player_nm: 'Anthony Martial', player_pos: 'FWD'},
          {player_id: '279', player_nm: 'Alex Nicolao Telles', player_pos: 'DEF'},
          {player_id: '280', player_nm: 'Dean Henderson', player_pos: 'GKP'},
          {player_id: '281', player_nm: 'Marcus Rashford', player_pos: 'MID'},
          {player_id: '282', player_nm: 'Donny van de Beek', player_pos: 'MID'},
          {player_id: '284', player_nm: 'Victor Lindelöf', player_pos: 'DEF'},
          {player_id: '285', player_nm: 'Scott McTominay', player_pos: 'MID'},
          {player_id: '286', player_nm: 'Eric Bailly', player_pos: 'DEF'},
          {player_id: '288', player_nm: 'Aaron Wan-Bissaka', player_pos: 'DEF'},
          {player_id: '289', player_nm: 'Mason Greenwood', player_pos: 'MID'},
          {player_id: '459', player_nm: 'Juan Mata', player_pos: 'MID'},
          {player_id: '485', player_nm: 'Jadon Sancho', player_pos: 'MID'},
          {player_id: '509', player_nm: 'Tom Heaton', player_pos: 'GKP'},
          {player_id: '510', player_nm: 'José Diogo Dalot Teixeira', player_pos: 'DEF'},
          {player_id: '511', player_nm: 'Andreas Pereira', player_pos: 'MID'},
          {player_id: '512', player_nm: 'Anthony Elanga', player_pos: 'MID'},
          {player_id: '555', player_nm: 'Raphaël Varane', player_pos: 'DEF'},
          {player_id: '579', player_nm: 'Cristiano Ronaldo dos Santos Aveiro', player_pos: 'FWD'},
          {player_id: '19', player_nm: 'Joseph Willock', player_pos: 'MID'},
          {player_id: '291', player_nm: 'Jonjo Shelvey', player_pos: 'MID'},
          {player_id: '292', player_nm: 'Matt Ritchie', player_pos: 'DEF'},
          {player_id: '293', player_nm: 'Ciaran Clark', player_pos: 'DEF'},
          {player_id: '294', player_nm: 'Karl Darlow', player_pos: 'GKP'},
          {player_id: '295', player_nm: 'Martin Dubravka', player_pos: 'GKP'},
          {player_id: '296', player_nm: 'Callum Wilson', player_pos: 'FWD'},
          {player_id: '297', player_nm: 'Jeff Hendrick', player_pos: 'MID'},
          {player_id: '298', player_nm: 'Ryan Fraser', player_pos: 'MID'},
          {player_id: '299', player_nm: 'Jamaal Lascelles', player_pos: 'DEF'},
          {player_id: '300', player_nm: 'Dwight Gayle', player_pos: 'FWD'},
          {player_id: '301', player_nm: 'Paul Dummett', player_pos: 'DEF'},
          {player_id: '302', player_nm: 'Javier Manquillo', player_pos: 'DEF'},
          {player_id: '303', player_nm: 'Emil Krafth', player_pos: 'DEF'},
          {player_id: '304', player_nm: 'Jacob Murphy', player_pos: 'MID'},
          {player_id: '305', player_nm: 'Fabian Schär', player_pos: 'DEF'},
          {player_id: '306', player_nm: 'Isaac Hayden', player_pos: 'MID'},
          {player_id: '307', player_nm: 'Allan Saint-Maximin', player_pos: 'FWD'},
          {player_id: '308', player_nm: 'Miguel Almirón', player_pos: 'MID'},
          {player_id: '309', player_nm: 'Sean Longstaff', player_pos: 'MID'},
          {player_id: '310', player_nm: 'Joelinton Cássio Apolinário de Lira', player_pos: 'FWD'},
          {player_id: '311', player_nm: 'Jamal Lewis', player_pos: 'DEF'},
          {player_id: '312', player_nm: 'Matthew Longstaff', player_pos: 'MID'},
          {player_id: '465', player_nm: 'Federico Fernández', player_pos: 'DEF'},
          {player_id: '513', player_nm: 'Freddie Woodman', player_pos: 'GKP'},
          {player_id: '514', player_nm: 'Mark Gillespie', player_pos: 'GKP'},
          {player_id: '599', player_nm: 'Joe White', player_pos: 'MID'},
          {player_id: '609', player_nm: 'Elliot Anderson', player_pos: 'MID'},
          {player_id: '145', player_nm: 'Billy Gilmour', player_pos: 'MID'},
          {player_id: '290', player_nm: 'Brandon Williams', player_pos: 'DEF'},
          {player_id: '313', player_nm: 'Michael McGovern', player_pos: 'GKP'},
          {player_id: '314', player_nm: 'Tim Krul', player_pos: 'GKP'},
          {player_id: '315', player_nm: 'Teemu Pukki', player_pos: 'FWD'},
          {player_id: '316', player_nm: 'Marco Stiepermann', player_pos: 'MID'},
          {player_id: '317', player_nm: 'Lukas Rupp', player_pos: 'MID'},
          {player_id: '318', player_nm: 'Kenny McLean', player_pos: 'MID'},
          {player_id: '319', player_nm: 'Grant Hanley', player_pos: 'DEF'},
          {player_id: '320', player_nm: 'Onel Hernández', player_pos: 'MID'},
          {player_id: '321', player_nm: 'Sam Byram', player_pos: 'DEF'},
          {player_id: '322', player_nm: 'Jordan Hugill', player_pos: 'FWD'},
          {player_id: '323', player_nm: 'Kieran Dowell', player_pos: 'MID'},
          {player_id: '324', player_nm: 'Christoph Zimmermann', player_pos: 'DEF'},
          {player_id: '325', player_nm: 'Todd Cantwell', player_pos: 'MID'},
          {player_id: '326', player_nm: 'Max Aarons', player_pos: 'DEF'},
          {player_id: '327', player_nm: 'Jacob Sørensen', player_pos: 'DEF'},
          {player_id: '328', player_nm: 'Przemyslaw Placheta', player_pos: 'MID'},
          {player_id: '329', player_nm: 'Adam Idah', player_pos: 'FWD'},
          {player_id: '330', player_nm: 'Josh Martin', player_pos: 'MID'},
          {player_id: '331', player_nm: 'Andrew Omobamidele', player_pos: 'DEF'},
          {player_id: '448', player_nm: 'Angus Gunn', player_pos: 'GKP'},
          {player_id: '449', player_nm: 'Milot Rashica', player_pos: 'MID'},
          {player_id: '456', player_nm: 'Ben Gibson', player_pos: 'DEF'},
          {player_id: '457', player_nm: 'Dimitris Giannoulis', player_pos: 'DEF'},
          {player_id: '471', player_nm: 'Pierre Lees-Melou', player_pos: 'MID'},
          {player_id: '515', player_nm: 'Bali Mumba', player_pos: 'DEF'},
          {player_id: '516', player_nm: 'Joshua Sargent', player_pos: 'FWD'},
          {player_id: '528', player_nm: 'Christos Tzolis', player_pos: 'MID'},
          {player_id: '580', player_nm: 'Ozan Kabak', player_pos: 'DEF'},
          {player_id: '581', player_nm: 'Mathias Normann', player_pos: 'MID'},
          {player_id: '332', player_nm: 'Theo Walcott', player_pos: 'MID'},
          {player_id: '333', player_nm: 'Fraser Forster', player_pos: 'GKP'},
          {player_id: '334', player_nm: 'Alex McCarthy', player_pos: 'GKP'},
          {player_id: '335', player_nm: 'Oriol Romeu Vidal', player_pos: 'MID'},
          {player_id: '336', player_nm: 'Nathan Redmond', player_pos: 'MID'},
          {player_id: '338', player_nm: 'Jack Stephens', player_pos: 'DEF'},
          {player_id: '339', player_nm: 'Stuart Armstrong', player_pos: 'MID'},
          {player_id: '341', player_nm: 'James Ward-Prowse', player_pos: 'MID'},
          {player_id: '342', player_nm: 'Kyle Walker-Peters', player_pos: 'DEF'},
          {player_id: '343', player_nm: 'Jan Bednarek', player_pos: 'DEF'},
          {player_id: '344', player_nm: 'Daniel NLundulu', player_pos: 'FWD'},
          {player_id: '345', player_nm: 'Che Adams', player_pos: 'FWD'},
          {player_id: '346', player_nm: 'Nathan Tella', player_pos: 'MID'},
          {player_id: '347', player_nm: 'William Smallbone', player_pos: 'MID'},
          {player_id: '348', player_nm: 'Michael Obafemi', player_pos: 'FWD'},
          {player_id: '349', player_nm: 'Ibrahima Diallo', player_pos: 'MID'},
          {player_id: '350', player_nm: 'Moussa Djenepo', player_pos: 'MID'},
          {player_id: '351', player_nm: 'Mohammed Salisu', player_pos: 'DEF'},
          {player_id: '460', player_nm: 'Romain Perraud', player_pos: 'DEF'},
          {player_id: '491', player_nm: 'Tino Livramento', player_pos: 'DEF'},
          {player_id: '517', player_nm: 'Mohamed Elyounoussi', player_pos: 'MID'},
          {player_id: '518', player_nm: 'Armando Broja', player_pos: 'FWD'},
          {player_id: '519', player_nm: 'Shane Long', player_pos: 'FWD'},
          {player_id: '525', player_nm: 'Adam Armstrong', player_pos: 'FWD'},
          {player_id: '546', player_nm: 'Yan Valery', player_pos: 'DEF'},
          {player_id: '567', player_nm: 'Lyanco Evangelista Silveira Neves Vojnovic', player_pos: 'DEF'},
          {player_id: '352', player_nm: 'Joe Hart', player_pos: 'GKP'},
          {player_id: '353', player_nm: 'Hugo Lloris', player_pos: 'GKP'},
          {player_id: '355', player_nm: 'Toby Alderweireld', player_pos: 'DEF'},
          {player_id: '356', player_nm: 'Erik Lamela', player_pos: 'MID'},
          {player_id: '357', player_nm: 'Harry Kane', player_pos: 'FWD'},
          {player_id: '358', player_nm: 'Serge Aurier', player_pos: 'DEF'},
          {player_id: '359', player_nm: 'Heung-Min Son', player_pos: 'MID'},
          {player_id: '360', player_nm: 'Matt Doherty', player_pos: 'DEF'},
          {player_id: '361', player_nm: 'Eric Dier', player_pos: 'DEF'},
          {player_id: '362', player_nm: 'Lucas Rodrigues Moura da Silva', player_pos: 'MID'},
          {player_id: '363', player_nm: 'Bamidele Alli', player_pos: 'MID'},
          {player_id: '364', player_nm: 'Ben Davies', player_pos: 'DEF'},
          {player_id: '365', player_nm: 'Pierre-Emile Højbjerg', player_pos: 'MID'},
          {player_id: '366', player_nm: 'Harry Winks', player_pos: 'MID'},
          {player_id: '367', player_nm: 'Davinson Sánchez', player_pos: 'DEF'},
          {player_id: '368', player_nm: 'Ryan Sessegnon', player_pos: 'DEF'},
          {player_id: '369', player_nm: 'Steven Bergwijn', player_pos: 'MID'},
          {player_id: '370', player_nm: 'Sergio Reguilón', player_pos: 'DEF'},
          {player_id: '371', player_nm: 'Japhet Tanganga', player_pos: 'DEF'},
          {player_id: '372', player_nm: 'Giovani Lo Celso', player_pos: 'MID'},
          {player_id: '373', player_nm: 'Oliver Skipp', player_pos: 'MID'},
          {player_id: '374', player_nm: 'Joe Rodon', player_pos: 'DEF'},
          {player_id: '375', player_nm: 'Tanguy Ndombele', player_pos: 'MID'},
          {player_id: '486', player_nm: 'Pierluigi Gollini', player_pos: 'GKP'},
          {player_id: '487', player_nm: 'Bryan Gil Salvatierra', player_pos: 'MID'},
          {player_id: '494', player_nm: 'Cristian Romero', player_pos: 'DEF'},
          {player_id: '520', player_nm: 'Dane Scarlett', player_pos: 'FWD'},
          {player_id: '588', player_nm: 'Emerson Aparecido Leite de Souza Junior', player_pos: 'DEF'},
          {player_id: '597', player_nm: 'Dilan Markanday', player_pos: 'MID'},
          {player_id: '598', player_nm: 'Tobi Omole', player_pos: 'DEF'},
          {player_id: '354', player_nm: 'Moussa Sissoko', player_pos: 'MID'},
          {player_id: '376', player_nm: 'Ben Foster', player_pos: 'GKP'},
          {player_id: '377', player_nm: 'Danny Rose', player_pos: 'DEF'},
          {player_id: '378', player_nm: 'Dan Gosling', player_pos: 'MID'},
          {player_id: '379', player_nm: 'Craig Cathcart', player_pos: 'DEF'},
          {player_id: '380', player_nm: 'Troy Deeney', player_pos: 'FWD'},
          {player_id: '381', player_nm: 'Tom Cleverley', player_pos: 'MID'},
          {player_id: '382', player_nm: 'Francisco Femenía Far', player_pos: 'DEF'},
          {player_id: '383', player_nm: 'Andre Gray', player_pos: 'FWD'},
          {player_id: '384', player_nm: 'Christian Kabasele', player_pos: 'DEF'},
          {player_id: '385', player_nm: 'Nathaniel Chalobah', player_pos: 'MID'},
          {player_id: '387', player_nm: 'William Troost-Ekong', player_pos: 'DEF'},
          {player_id: '388', player_nm: 'Stipe Perica', player_pos: 'FWD'},
          {player_id: '389', player_nm: 'Daniel Bachmann', player_pos: 'GKP'},
          {player_id: '390', player_nm: 'Adam Masina', player_pos: 'DEF'},
          {player_id: '391', player_nm: 'Ken Sema', player_pos: 'MID'},
          {player_id: '392', player_nm: 'Philip Zinckernagel', player_pos: 'MID'},
          {player_id: '393', player_nm: 'Isaac Success Ajayi', player_pos: 'FWD'},
          {player_id: '394', player_nm: 'Ayotomiwa Dele-Bashiru', player_pos: 'MID'},
          {player_id: '395', player_nm: 'Ashley Fletcher', player_pos: 'FWD'},
          {player_id: '396', player_nm: 'Francisco Sierralta', player_pos: 'DEF'},
          {player_id: '397', player_nm: 'Domingos Quina', player_pos: 'MID'},
          {player_id: '398', player_nm: 'Marc Navarro', player_pos: 'DEF'},
          {player_id: '399', player_nm: 'Ismaila Sarr', player_pos: 'MID'},
          {player_id: '400', player_nm: 'Jeremy Ngakia', player_pos: 'DEF'},
          {player_id: '401', player_nm: 'Ben Wilmot', player_pos: 'DEF'},
          {player_id: '402', player_nm: 'Joseph Hungbo', player_pos: 'MID'},
          {player_id: '403', player_nm: 'Imrân Louza', player_pos: 'MID'},
          {player_id: '404', player_nm: 'João Pedro Junqueira de Jesus', player_pos: 'FWD'},
          {player_id: '405', player_nm: 'Kwadwo Baah', player_pos: 'MID'},
          {player_id: '450', player_nm: 'Emmanuel Dennis', player_pos: 'FWD'},
          {player_id: '454', player_nm: 'Matthew Pollock', player_pos: 'DEF'},
          {player_id: '467', player_nm: 'Oghenekaro Peter Etebo', player_pos: 'MID'},
          {player_id: '468', player_nm: 'Joshua King', player_pos: 'FWD'},
          {player_id: '469', player_nm: 'Adedapo Awokoya-Mebude', player_pos: 'FWD'},
          {player_id: '472', player_nm: 'Juan Camilo Hernández Suárez', player_pos: 'FWD'},
          {player_id: '495', player_nm: 'Juraj Kucka', player_pos: 'MID'},
          {player_id: '557', player_nm: 'Ozan Tufan', player_pos: 'MID'},
          {player_id: '574', player_nm: 'Robert Elliot', player_pos: 'GKP'},
          {player_id: '618', player_nm: 'Nicolas Nkoulou', player_pos: 'DEF'},
          {player_id: '128', player_nm: 'Kurt Zouma', player_pos: 'DEF'},
          {player_id: '406', player_nm: 'Mark Noble', player_pos: 'MID'},
          {player_id: '407', player_nm: 'Darren Randolph', player_pos: 'GKP'},
          {player_id: '408', player_nm: 'Lukasz Fabianski', player_pos: 'GKP'},
          {player_id: '409', player_nm: 'Angelo Ogbonna', player_pos: 'DEF'},
          {player_id: '410', player_nm: 'Winston Reid', player_pos: 'DEF'},
          {player_id: '411', player_nm: 'Aaron Cresswell', player_pos: 'DEF'},
          {player_id: '412', player_nm: 'Andriy Yarmolenko', player_pos: 'MID'},
          {player_id: '413', player_nm: 'Michail Antonio', player_pos: 'FWD'},
          {player_id: '414', player_nm: 'Craig Dawson', player_pos: 'DEF'},
          {player_id: '415', player_nm: 'Ryan Fredericks', player_pos: 'DEF'},
          {player_id: '416', player_nm: 'Manuel Lanzini', player_pos: 'MID'},
          {player_id: '417', player_nm: 'Arthur Masuaku', player_pos: 'DEF'},
          {player_id: '418', player_nm: 'Vladimir Coufal', player_pos: 'DEF'},
          {player_id: '419', player_nm: 'Saïd Benrahma', player_pos: 'MID'},
          {player_id: '420', player_nm: 'Jarrod Bowen', player_pos: 'MID'},
          {player_id: '421', player_nm: 'Declan Rice', player_pos: 'MID'},
          {player_id: '422', player_nm: 'Tomas Soucek', player_pos: 'MID'},
          {player_id: '423', player_nm: 'Pablo Fornals', player_pos: 'MID'},
          {player_id: '424', player_nm: 'Issa Diop', player_pos: 'DEF'},
          {player_id: '425', player_nm: 'Ben Johnson', player_pos: 'DEF'},
          {player_id: '489', player_nm: 'Alphonse Areola', player_pos: 'GKP'},
          {player_id: '521', player_nm: 'Frederik Alves', player_pos: 'DEF'},
          {player_id: '522', player_nm: 'Conor Coventry', player_pos: 'MID'},
          {player_id: '554', player_nm: 'Jamal Baptiste', player_pos: 'DEF'},
          {player_id: '582', player_nm: 'Nikola Vlasic', player_pos: 'MID'},
          {player_id: '589', player_nm: 'Alex Kral', player_pos: 'MID'},
          {player_id: '617', player_nm: 'Harrison Ashby', player_pos: 'DEF'},
          {player_id: '426', player_nm: 'João Filipe Iria Santos Moutinho', player_pos: 'MID'},
          {player_id: '427', player_nm: 'Rui Pedro dos Santos Patrício', player_pos: 'GKP'},
          {player_id: '428', player_nm: 'Willy Boly', player_pos: 'DEF'},
          {player_id: '429', player_nm: 'Conor Coady', player_pos: 'DEF'},
          {player_id: '430', player_nm: 'Raúl Jiménez', player_pos: 'FWD'},
          {player_id: '431', player_nm: 'Romain Saïss', player_pos: 'DEF'},
          {player_id: '432', player_nm: 'Fernando Marçal', player_pos: 'DEF'},
          {player_id: '433', player_nm: 'Jonathan Castro Otto', player_pos: 'DEF'},
          {player_id: '434', player_nm: 'Leander Dendoncker', player_pos: 'MID'},
          {player_id: '435', player_nm: 'Adama Traoré', player_pos: 'MID'},
          {player_id: '436', player_nm: 'Rúben Diogo da Silva Neves', player_pos: 'MID'},
          {player_id: '437', player_nm: 'Nélson Cabral Semedo', player_pos: 'DEF'},
          {player_id: '438', player_nm: 'Daniel Castelo Podence', player_pos: 'MID'},
          {player_id: '439', player_nm: 'Max Kilman', player_pos: 'DEF'},
          {player_id: '440', player_nm: 'Morgan Gibbs-White', player_pos: 'MID'},
          {player_id: '441', player_nm: 'Pedro Lomba Neto', player_pos: 'MID'},
          {player_id: '442', player_nm: 'Owen Otasowie', player_pos: 'MID'},
          {player_id: '443', player_nm: 'Ki-Jana Hoever', player_pos: 'DEF'},
          {player_id: '444', player_nm: 'Andreas Söndergaard', player_pos: 'GKP'},
          {player_id: '445', player_nm: 'Fabio Silva', player_pos: 'FWD'},
          {player_id: '446', player_nm: 'Yerson Mosquera Valdelamar', player_pos: 'DEF'},
          {player_id: '452', player_nm: 'John Ruddy', player_pos: 'GKP'},
          {player_id: '461', player_nm: 'Francisco Machado Mota de Castro Trincão', player_pos: 'MID'},
          {player_id: '470', player_nm: 'Rayan Ait Nouri', player_pos: 'DEF'},
          {player_id: '475', player_nm: 'José Malheiro de Sá', player_pos: 'GKP'},
          {player_id: '523', player_nm: 'Patrick Cutrone', player_pos: 'FWD'},
          {player_id: '547', player_nm: 'Luke Cundle', player_pos: 'MID'},
          {player_id: '548', player_nm: 'Chem Campbell', player_pos: 'MID'},
          {player_id: '549', player_nm: 'Christian Marques', player_pos: 'DEF'},
          {player_id: '583', player_nm: 'Hee-Chan Hwang', player_pos: 'FWD'},
          {player_id: '611', player_nm: 'Louie Moulden', player_pos: 'GKP'},
          {player_id: '621', player_nm: 'James Storer', player_pos: 'GKP'},

         ]);
      });
  };
  